---
bases:
  - ../../bases/helmDefaults.yaml
  - ../../bases/environments.yaml

---
releases:
- name: whoami
  chart: ../../../charts/whoami
  namespace: whoami
  createNamespace: true
  missingFileHandler: Warn
  installed: {{ .Values | get "whoami.installed" "false" }}
  values:
    - whoami-values.yaml.gotmpl
