---
bases:
  - ../../base/helmDefaults.yaml
  - ../../base/environments.yaml
  - ../../../environments/environments.yaml

---
repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: promtail
  chart: grafana/promtail
  version: {{ .Values.promtail | get "chart_version" nil | quote }}
  namespace: {{ .Values.promtail.namespace }}
  installed: {{ .Values.promtail.installed }}
  createNamespace: true
  missingFileHandler: Warn
  values:
    - "{{`{{ .Release.Name }}`}}-values.yaml.gotmpl"
    - "../../../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl"
  secrets:
    - "../../../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}/secrets.enc.yaml"
