{{- range .Values.clusterIssuers }}
---
# raw issuer: {{ . | toJson }}
{{- $enabled := printf "%t" .enabled }}
{{- if regexMatch "nil" $enabled }}{{- $enabled = "true" }}{{- end }}
{{- if (eq $enabled "true") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .metadata.name }}
  labels:
    {{- include "cert-manager-issuers.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "2"
spec:
  {{- .spec | toYaml | nindent 2 }}
{{- end }}
{{- end }}
