{{- range .Values.issuers }}
---
# raw issuer: {{ . | toJson }}
{{- $enabled := printf "%t" .enabled }}
{{- if regexMatch "nil" $enabled }}{{- $enabled = "true" }}{{- end }}
{{- if (eq $enabled "true") }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .metadata.name }}
  labels:
    {{- include "cert-manager-issuers.labels" $ | nindent 4 }}
spec:
  {{- .spec | toYaml | nindent 2 }}
{{- end }}
{{- end }}
