---
core_namespaces:
  installed: false # true
  namespaces:
#    cert-manager: {}
#    ingress-nginx: {}
#    argocd: {}
    loki: {}
#    monitoring: {}
#    promtail: {}
    whoami: {}

ingress_nginx:
  installed: false # true
  chart_version: v4.9.1
  name: "ingress-nginx"
  ingress_class: "nginx"
  ingress_namespace: "ingress-nginx"
  kind: "DaemonSet"

ingress_nginx_admin:
  installed: false # true
  chart_version: v4.9.1
  name: "ingress-nginx-admin"
  ingress_class: "nginx-admin"
  ingress_namespace: "ingress-nginx-admin"
  kind: "DaemonSet"
  controller_value: "k8s.io/ingress-nginx-admin"
  http: 80
  https: 443

cert_manager:
  installed: false # true
  chart_version: v1.14.4
  namespace: "cert-manager"
  ingress_class: "nginx"
  ingress_name: ingress-nginx
  ingress_namespace: ingress-nginx

cert_manager_issuer:
  installed: false # true
  namespace: "cert-manager"

loki:
  installed: false # true
  chart_version: 5.47.1
  namespace: "loki"

prometheus_operator_crds:
  installed: false # true
  namespace: "monitoring"

prometheus:
  installed: false # true
  chart_version: 57.1.1
  namespace: "monitoring"
  ingress_class: nginx
  ingress_namespace: ingress-nginx
  ingress_name: ingress-nginx

promtail:
  installed: false # true
  chart_version: 6.15.5
  namespace: "promtail"

argocd:
  installed: false # true
  chart_version: 6.7.2
  namespace: "argocd"
  ingress_class: nginx
  ingress_namespace: ingress-nginx
  ingress_name: ingress-nginx
