---
ingress_nginx:
  installed: true
  # for local development cluster: Deployment is enough
  kind: "Deployment"
  # for other cluster: DaemonSet is better (one pod to each node)
  # kind: "DaemonSet"
  # certificate secret
  # default_ssl_certificate: "127.0.0.1.nip.io"

loki:
  installed: true
promtail:
  installed: true

prometheus:
  installed: true
  grafana_hostname: grafana.127.0.0.1.nip.io
  alertmanager_hostname: alertmanager.127.0.0.1.nip.io
  prometheus_hostname: prometheus.127.0.0.1.nip.io

  # define which ingress to use
  ingress_class: nginx
  ingress_namespace: ingress-nginx
  ingress_name: ingress-nginx

whoami:
  installed: true
  whoami_hostname: whoami.127.0.0.1.nip.io
  ingress_class: nginx
#  annotations:
#    nginx.ingress.kubernetes.io/auth-type: basic
#    nginx.ingress.kubernetes.io/auth-secret: ingress-nginx/basic-auth
#    nginx.ingress.kubernetes.io/auth-secret-type: auth-file
#    nginx.ingress.kubernetes.io/auth-realm: "Progress Authentication"
