---
bases:
  - ../../bases/helmDefaults.yaml
  - ../../bases/environments.yaml

---
repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus-operator-crds
  chart: prometheus-community/prometheus-operator-crds
  version: {{ .Values.prometheus_operator_crds | get "chart_version" nil | quote }}
  namespace: {{ .Values.prometheus_operator_crds.namespace }}
  createNamespace: true
  installed: {{ .Values.prometheus_operator_crds.installed }}

- name: prometheus
  chart: prometheus-community/kube-prometheus-stack
  version: {{ .Values.prometheus | get "chart_version" nil | quote }}
  namespace: {{ .Values.prometheus.namespace }}
  createNamespace: true
  installed: {{ .Values.prometheus.installed }}
  missingFileHandler: Warn
#  needs:
#    # - kube-system/namespaces
#    - "{{ .Values.prometheus_operator_crds.namespace }}/prometheus-operator-crds"
#    - "{{ .Values.loki.namespace }}/loki"
#    #- "{{ .Values.prometheus.ingress_namespace }}/{{ .Values.prometheus.ingress_name }}"
  values:
    - "{{`{{ .Release.Name }}`}}-values.yaml.gotmpl"
    - "env/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}-values.yaml.gotmpl"
#
#  Uncomment to enable secrets values
#
  secrets:
    - "../../../secrets/env/{{ .Environment.Name  }}/grafana-secrets.yaml.enc"
