---
bases:
  - ../../base/helmDefaults.yaml
  - ../../base/environments.yaml
  - ../../../environments/environments.yaml

---
repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
- name: argocd
  chart: argo/argo-cd
  version: {{ .Values.argocd | get "chart_version" nil | quote }}
  namespace: {{ .Values.argocd | get "namespace" "argocd" }}
  installed: {{ .Values.argocd | get "installed" false }}
  createNamespace: true
  missingFileHandler: Warn
  values:
    - "../{{`{{ .Release.Name }}`}}/{{`{{ .Release.Name }}`}}-values.yaml.gotmpl"
    - "../../../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl"
  secrets:
    - "../../../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}/secrets.enc.yaml"

- name: argocd-basic-auth
  chart: ../../../charts/ingress-auth
  version: {{ .Values.argocd_basic_auth | get "chart_version" nil | quote }}
  namespace: {{ .Values.argocd_basic_auth | get "namespace" "ingress-nginx" }}
  installed: {{ .Values.argocd_basic_auth | get "installed" false }}
  verify: false
  missingFileHandler: Warn
  values:
    - "../{{`{{ .Release.Name }}`}}/{{`{{ .Release.Name }}`}}-values.yaml.gotmpl"
    - "../../../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl"
  secrets:
    - "../../../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}/secrets.enc.yaml"
