{{- if .Values.auth.users }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "ingress-auth.fullname" . }}
  namespace: {{ include "ingress-auth.namespace" . }}
  labels:
    {{- include "ingress-auth.labels" . | nindent 4 }}
data:
  {{- range .Values.auth.users }}
  {{ .username }}: {{ .password | b64enc }}
  {{- end }}
{{- end }}
