---
bases:
  - ../../base/helmDefaults.yaml
  - ../../base/environments.yaml
  - ../../../environments/environments.yaml

---
repositories:
- name: portainer
  url: https://portainer.github.io/k8s/

releases:
- name: portainer
  chart: portainer/portainer
  installed: {{ .Values.portainer | get "installed" false }}
  namespace: {{ .Values.portainer | get "namespace" "default" }}
  verify: false
  createNamespace: true
  missingFileHandler: Warn
  values:
    - "{{`{{ .Release.Name }}`}}-values.yaml.gotmpl"
    - "../../../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl"
  secrets:
    - "../../../environments/{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}/secrets.enc.yaml"
