---
bases:
  - bases/helmDefaults.yaml
  - bases/environments.yaml

helmfiles:
- path: releases/prometheus-stack/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 4 }}

missingFileHandler: Warn
