---
{{- $envValuesDir := print (regexReplaceAll "/releases/[^/]+$" (env "PWD") "") "/helmfile.d/environments" }}

environments:
  default:
    values:
      - "{{ $envValuesDir }}/common.yaml"
      - "{{ $envValuesDir }}/{{ .Environment.Name }}.yaml"
  local:
    values:
      - "{{ $envValuesDir }}/common.yaml"
      - "{{ $envValuesDir }}/{{ .Environment.Name }}.yaml"
  dev:
    values:
      - "{{ $envValuesDir }}/common.yaml"
      - "{{ $envValuesDir }}/{{ .Environment.Name }}.yaml"
