---
core_namespaces:
  installed: true
  namespaces:
    cert-manager: {}
    ingress-nginx: {}
workload_namespaces:
  installed: true
  namespaces:
    argocd: {}
    monitoring: {}
    promtail: {}
    loki: {}
    whoami: {}

cert_manager:
  installed: true

cert_manager_secrets:
  installed: true

cert_manager_issuer:
  installed: true
  clusterIssuers:
    - metadata:
        name: ca-cluster-issuer
      spec:
        ca:
          secretName: ca-key-pair
#      - metadata:
#          name: selfsigned-cluster-issuer
#        spec:
#          selfSigned: {}

ingress_nginx:
  installed: true
  # for local development cluster: Deployment is enough
  kind: "Deployment"
  # for other cluster: DaemonSet is better (one pod to each node)
  # kind: "DaemonSet"
  #
  # certificate secret need tls secret 127.0.0.1.nip.io
  # default_ssl_certificate: "127.0.0.1.nip.io"
  nodeSelector:
    ingress-ready: "true"

loki:
  installed: true
promtail:
  installed: true

prometheus_operator_crds:
  installed: false

prometheus:
  installed: true
  grafana_hostname: grafana.127.0.0.1.nip.io
  alertmanager_hostname: alertmanager.127.0.0.1.nip.io
  prometheus_hostname: prometheus.127.0.0.1.nip.io
  prometheus:
    nginx_enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "ca-cluster-issuer"
    tls:
      - hosts:
        - prometheus.127.0.0.1.nip.io
        secretName: prometheus.127.0.0.1.nip.io
    hosts:
      - prometheus.127.0.0.1.nip.io
  alertmanager:
    nginx_enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "ca-cluster-issuer"
    tls:
      - hosts:
        - alertmanager.127.0.0.1.nip.io
        secretName: alertmanager.127.0.0.1.nip.io
    hosts:
      - alertmanager.127.0.0.1.nip.io
  grafana:
    nginx_enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "ca-cluster-issuer"
    tls:
      - hosts:
        - grafana.127.0.0.1.nip.io
        secretName: grafana.127.0.0.1.nip.io
    hosts:
      - grafana.127.0.0.1.nip.io
  # define which ingress to use
  ingress_class: nginx
  ingress_namespace: ingress-nginx
  ingress_name: ingress-nginx

argocd:
  installed: true

core_extra_argocd:
  installed: false

whoami:
  installed: true
  ingress_class: nginx
  tls:
    - hosts:
      - whoami.127.0.0.1.nip.io
      secretName: whoami.127.0.0.1.nip.io
  hosts:
    - host: whoami.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix

  annotations:
    # generate ssl certificate
    # cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
    cert-manager.io/cluster-issuer: "ca-cluster-issuer"

    # enable basic auth
#    nginx.ingress.kubernetes.io/auth-type: basic
#    nginx.ingress.kubernetes.io/auth-secret: ingress-nginx/basic-auth
#    nginx.ingress.kubernetes.io/auth-secret-type: auth-file
#    nginx.ingress.kubernetes.io/auth-realm: "Progress Authentication"

