name: "[test helmfiles releases]"
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}-test-workloads"
  cancel-in-progress: true

jobs:
  ci-test-helmfiles:
    strategy:
      fail-fast: false
      matrix:
        # kubernetes releases
        k8s: [v1.27.13, v1.28.9, v1.29.4]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Prerequisite installations"
        run: |
          echo "install tooling"
          ( curl -Ls https://raw.githubusercontent.com/numerique-gouv/dk8s/main/scripts/install-prereq.sh | bash ) || exit $?

      - name: lint
        run: |
          echo "lint files"
          time make lint HELMFILE_FILE=helmfile.d/cluster-configure-core
          time make lint HELMFILE_FILE=helmfile.d/cluster-workload

      - name: "Create local kubernetes ${{ matrix.k8s }} cluster"
        run: |
          make ci-bootstrap-local-cluster K8S_VERSION=${{ matrix.k8s }}
          kubectl get nodes -A

      - name: Test on local environment
        run: |
          echo "Install local root CA"
          time make local-root-ca
          echo "Sync releases"
          time make apply HELMFILE_FILE=helmfile.d/cluster-configure-core
          time make apply HELMFILE_FILE=helmfile.d/cluster-workload
          helm list -A
          echo "Test local url"
          time make ci-local-tests
          echo "Destroy resources"
          time make destroy

      - name: Teardown
        if: always()
        run: |
          echo "Destroy cluster ${{ matrix.k8s }}"
          make ci-delete-local-cluster K8S_VERSION=${{ matrix.k8s }}
